/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Hash a buffer using BLAKE3
 * Returns a 32-byte hash as Buffer
 */
export declare function hashBuffer(data: Buffer): Buffer
/** Hash multiple buffers together (for Merkle tree nodes) */
export declare function hashBuffers(buffers: Array<Buffer>): Buffer
/**
 * Combine two 32-byte hashes into one
 * Used for Merkle tree internal nodes
 */
export declare function combineHashes(a: Buffer, b: Buffer): Buffer
/**
 * Hash a file in chunks, returning all chunk hashes
 * This is async to avoid blocking the JS thread
 */
export declare function hashFileChunks(path: string, chunkSize: number): Promise<Array<Buffer>>
/** A proof step in a Merkle proof */
export interface ProofStep {
  hash: Buffer
  isLeft: boolean
}
/** A subtree proof */
export interface SubtreeProof {
  node: Buffer
  level: number
  index: number
  proof: Array<ProofStep>
  root: Buffer
}
/** Result of building a Merkle tree */
export interface MerkleTreeResult {
  root: Buffer
  leafCount: number
}
/**
 * Build a Merkle tree from an array of 32-byte leaf hashes
 * Returns the root hash and leaf count
 */
export declare function buildMerkleTree(leafHashes: Array<Buffer>): MerkleTreeResult
/** Get just the Merkle root from leaf hashes */
export declare function getMerkleRoot(leafHashes: Array<Buffer>): Buffer
/**
 * Generate a subtree proof for a given level and index
 * Takes leaf hashes, level (0 = leaves), and index at that level
 */
export declare function generateSubtreeProof(leafHashes: Array<Buffer>, level: number, index: number): SubtreeProof
/** Verify a subtree proof */
export declare function verifySubtreeProof(node: Buffer, proof: Array<ProofStep>, expectedRoot: Buffer): boolean
/** Build a Merkle tree from a file path (parallel chunk hashing) */
export declare function buildFileMerkleTree(path: string, chunkSize: number): Promise<MerkleTreeResult>
/**
 * Count the number of set bits in a bitfield buffer
 * Uses popcount intrinsic for O(n/8) complexity instead of O(n)
 */
export declare function bitfieldCount(buffer: Buffer): number
/**
 * Get all set bit indices from a bitfield buffer
 * Returns array of indices where bits are set
 */
export declare function bitfieldGetSetIndices(buffer: Buffer): Array<number>
/** Check if a bit is set at the given index */
export declare function bitfieldGet(buffer: Buffer, index: number): boolean
/**
 * Set a bit at the given index
 * Returns a new buffer with the bit set
 */
export declare function bitfieldSet(buffer: Buffer, index: number): Buffer
/**
 * Clear a bit at the given index
 * Returns a new buffer with the bit cleared
 */
export declare function bitfieldClear(buffer: Buffer, index: number): Buffer
/** Create a new bitfield buffer of the given size (in bits) */
export declare function bitfieldNew(size: number): Buffer
/** Check if all bits are set */
export declare function bitfieldIsFull(buffer: Buffer, size: number): boolean
/** Check if no bits are set */
export declare function bitfieldIsEmpty(buffer: Buffer): boolean
/** Verify a single chunk against its expected hash */
export declare function verifyChunk(data: Buffer, expectedHash: Buffer): boolean
/** Verify multiple chunks against their expected hashes in parallel */
export declare function verifyChunksBatch(chunks: Array<Buffer>, hashes: Array<Buffer>): Array<boolean>
