// This file is autogenerated by the hyperdb compiler
/* eslint-disable camelcase */

import { IndexEncoder, c, b4a } from 'hyperdb/runtime'
import { version, getEncoding, setVersion } from './messages.js'

const versions = { schema: version, db: 1 }

// '@userdb/device' collection key
const collection0_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 0 })

function collection0_indexify (record) {
  const a = record.deviceId
  return a === undefined ? [] : [a]
}

// '@userdb/device' value encoding
const collection0_enc = getEncoding('@userdb/device/hyperdb#0')

// '@userdb/device' reconstruction function
function collection0_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection0_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection0.decodedVersion = c.uint.decode(state)
  const record = collection0_enc.decode(state)
  record.deviceId = key[0]
  return record
}
// '@userdb/device' key reconstruction function
function collection0_reconstruct_key (keyBuf) {
  const key = collection0_key.decode(keyBuf)
  return {
    deviceId: key[0]
  }
}

// '@userdb/device'
const collection0 = {
  name: '@userdb/device',
  id: 0,
  version: 1,
  encodeKey (record) {
    const key = [record.deviceId]
    return collection0_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection0_key.encodeRange({
      gt: gt ? collection0_indexify(gt) : null,
      lt: lt ? collection0_indexify(lt) : null,
      gte: gte ? collection0_indexify(gte) : null,
      lte: lte ? collection0_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection0_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection0_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection0_reconstruct,
  reconstructKey: collection0_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@userdb/device-by-user' collection key
const index1_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 1 })

function index1_indexify (record) {
  const arr = []

  const a0 = record.userIdentity
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.deviceId
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.deviceId
  if (a2 === undefined) return arr
  arr.push(a2)

  return arr
}

// '@userdb/device-by-user'
const index1 = {
  name: '@userdb/device-by-user',
  version: 1,
  id: 1,
  encodeKey (record) {
    return index1_key.encode(index1_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index1_key.encodeRange({
      gt: gt ? index1_indexify(gt) : null,
      lt: lt ? index1_indexify(lt) : null,
      gte: gte ? index1_indexify(gte) : null,
      lte: lte ? index1_indexify(lte) : null
    })
  },
  encodeValue: (record) => index1.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index1_key.encode([record.userIdentity, record.deviceId, record.deviceId])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection0.indexes.length,
  collection: collection0
}
collection0.indexes.push(index1)

// '@userdb/friend' collection key
const collection2_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 2 })

function collection2_indexify (record) {
  const a = record.identityKey
  return a === undefined ? [] : [a]
}

// '@userdb/friend' value encoding
const collection2_enc = getEncoding('@userdb/friend/hyperdb#2')

// '@userdb/friend' reconstruction function
function collection2_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection2_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection2.decodedVersion = c.uint.decode(state)
  const record = collection2_enc.decode(state)
  record.identityKey = key[0]
  return record
}
// '@userdb/friend' key reconstruction function
function collection2_reconstruct_key (keyBuf) {
  const key = collection2_key.decode(keyBuf)
  return {
    identityKey: key[0]
  }
}

// '@userdb/friend'
const collection2 = {
  name: '@userdb/friend',
  id: 2,
  version: 1,
  encodeKey (record) {
    const key = [record.identityKey]
    return collection2_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection2_key.encodeRange({
      gt: gt ? collection2_indexify(gt) : null,
      lt: lt ? collection2_indexify(lt) : null,
      gte: gte ? collection2_indexify(gte) : null,
      lte: lte ? collection2_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection2_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection2_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection2_reconstruct,
  reconstructKey: collection2_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@userdb/setting' collection key
const collection3_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 3 })

function collection3_indexify (record) {
  const a = record.key
  return a === undefined ? [] : [a]
}

// '@userdb/setting' value encoding
const collection3_enc = getEncoding('@userdb/setting/hyperdb#3')

// '@userdb/setting' reconstruction function
function collection3_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection3_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection3.decodedVersion = c.uint.decode(state)
  const record = collection3_enc.decode(state)
  record.key = key[0]
  return record
}
// '@userdb/setting' key reconstruction function
function collection3_reconstruct_key (keyBuf) {
  const key = collection3_key.decode(keyBuf)
  return {
    key: key[0]
  }
}

// '@userdb/setting'
const collection3 = {
  name: '@userdb/setting',
  id: 3,
  version: 1,
  encodeKey (record) {
    const key = [record.key]
    return collection3_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection3_key.encodeRange({
      gt: gt ? collection3_indexify(gt) : null,
      lt: lt ? collection3_indexify(lt) : null,
      gte: gte ? collection3_indexify(gte) : null,
      lte: lte ? collection3_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection3_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection3_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection3_reconstruct,
  reconstructKey: collection3_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

const collections = [
  collection0,
  collection2,
  collection3
]

const indexes = [
  index1
]

export default { versions, collections, indexes, resolveCollection, resolveIndex }

function resolveCollection (name) {
  switch (name) {
    case '@userdb/device': return collection0
    case '@userdb/friend': return collection2
    case '@userdb/setting': return collection3
    default: return null
  }
}

function resolveIndex (name) {
  switch (name) {
    case '@userdb/device-by-user': return index1
    default: return null
  }
}
