// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @userdb/device
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.deviceId)
    c.string.preencode(state, m.name)
    c.fixed32.preencode(state, m.publicKey)
    c.string.preencode(state, m.userIdentity)
    c.buffer.preencode(state, m.proof)
    c.uint.preencode(state, m.addedAt)
    state.end++ // max flag is 1 so always one byte

    if (m.lastSeen) c.uint.preencode(state, m.lastSeen)
  },
  encode(state, m) {
    const flags = m.lastSeen ? 1 : 0

    c.string.encode(state, m.deviceId)
    c.string.encode(state, m.name)
    c.fixed32.encode(state, m.publicKey)
    c.string.encode(state, m.userIdentity)
    c.buffer.encode(state, m.proof)
    c.uint.encode(state, m.addedAt)
    c.uint.encode(state, flags)

    if (m.lastSeen) c.uint.encode(state, m.lastSeen)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.fixed32.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.buffer.decode(state)
    const r5 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      deviceId: r0,
      name: r1,
      publicKey: r2,
      userIdentity: r3,
      proof: r4,
      addedAt: r5,
      lastSeen: (flags & 1) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @userdb/friend
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.identityKey)
    state.end++ // max flag is 2 so always one byte

    if (m.name) c.string.preencode(state, m.name)
    c.uint.preencode(state, m.addedAt)
    if (m.proof) c.buffer.preencode(state, m.proof)
  },
  encode(state, m) {
    const flags = (m.name ? 1 : 0) | (m.proof ? 2 : 0)

    c.string.encode(state, m.identityKey)
    c.uint.encode(state, flags)

    if (m.name) c.string.encode(state, m.name)
    c.uint.encode(state, m.addedAt)
    if (m.proof) c.buffer.encode(state, m.proof)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      identityKey: r0,
      name: (flags & 1) !== 0 ? c.string.decode(state) : null,
      addedAt: c.uint.decode(state),
      proof: (flags & 2) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @userdb/setting
const encoding2 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.string.preencode(state, m.value)
    c.uint.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    c.string.encode(state, m.key)
    c.string.encode(state, m.value)
    c.uint.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)

    return {
      key: r0,
      value: r1,
      updatedAt: r2
    }
  }
}

// @userdb/device/hyperdb#0
const encoding3 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.fixed32.preencode(state, m.publicKey)
    c.string.preencode(state, m.userIdentity)
    c.buffer.preencode(state, m.proof)
    c.uint.preencode(state, m.addedAt)
    state.end++ // max flag is 1 so always one byte

    if (m.lastSeen) c.uint.preencode(state, m.lastSeen)
  },
  encode(state, m) {
    const flags = m.lastSeen ? 1 : 0

    c.string.encode(state, m.name)
    c.fixed32.encode(state, m.publicKey)
    c.string.encode(state, m.userIdentity)
    c.buffer.encode(state, m.proof)
    c.uint.encode(state, m.addedAt)
    c.uint.encode(state, flags)

    if (m.lastSeen) c.uint.encode(state, m.lastSeen)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.fixed32.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.buffer.decode(state)
    const r5 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      deviceId: null,
      name: r1,
      publicKey: r2,
      userIdentity: r3,
      proof: r4,
      addedAt: r5,
      lastSeen: (flags & 1) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @userdb/friend/hyperdb#2
const encoding4 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.name) c.string.preencode(state, m.name)
    c.uint.preencode(state, m.addedAt)
    if (m.proof) c.buffer.preencode(state, m.proof)
  },
  encode(state, m) {
    const flags = (m.name ? 1 : 0) | (m.proof ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.name) c.string.encode(state, m.name)
    c.uint.encode(state, m.addedAt)
    if (m.proof) c.buffer.encode(state, m.proof)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      identityKey: null,
      name: (flags & 1) !== 0 ? c.string.decode(state) : null,
      addedAt: c.uint.decode(state),
      proof: (flags & 2) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @userdb/setting/hyperdb#3
const encoding5 = {
  preencode(state, m) {
    c.string.preencode(state, m.value)
    c.uint.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    c.string.encode(state, m.value)
    c.uint.encode(state, m.updatedAt)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)

    return {
      key: null,
      value: r1,
      updatedAt: r2
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@userdb/device':
      return encoding0
    case '@userdb/friend':
      return encoding1
    case '@userdb/setting':
      return encoding2
    case '@userdb/device/hyperdb#0':
      return encoding3
    case '@userdb/friend/hyperdb#2':
      return encoding4
    case '@userdb/setting/hyperdb#3':
      return encoding5
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
